# Taken from https://github.com/kikito/middleclass/blob/master/.travis.yml
os: linux
language: python
sudo: false

addons:
  apt:
    packages:
      - libev-dev

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

matrix:
  allow_failures:
    - env: LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks make rockspec/*-master-1.rockspec
  - luarocks install luasec # for tests

script:
  - luacheck --std min+busted src/copas/*.lua test/*.lua
  - busted --verbose --coverage --pattern=test test

after_success:
  - luacov-coveralls --exclude "test" --exclude "lua_install"

notifications:
  recipients:
    - alban@linard.fr
  email:
    on_success: change
    on_failure: always
